### ISSUE TITLE
Separação de Projetos - Responsabilidade Única

### ISSUE THREAD

**Issue by hernandev** [pjbank/pjbank-php-sdk#13]
Olá, tenho uma proposta para que esse pacote seja refatorando em 3 pacotes:

- pjbank/php-sdk-core
- pjbank/php-sdk-recebimentos
- pjbank/php-sdk-conta-digital

Dessa forma fica mais fácil separar o código de cada funcionalidade, e quem uma só um dos serviços não é obrigado a instalar dependências desnecessárias.

Posso fazer esse trampo, se criar os projetos, ou posso criar separadamente, e você forka.

Pode manter os créditos de copyright, caso eu faça do zero, seguindo essa base, por mim é tranquilo.

Obrigado

**Comment by msfidelis** [comment]
Acho que não será necessário modularizar tanto de primeiro momento, pelo menos não na primeira versão. As classes são bem pequenas e a `Conta Digital` irá herdar todos os recursos do `recebimento`. Acho que seria um esforço que não traria tanto retorno agora. 

O PJBank é uma empresa que segue os padrões de qualidade e segurança por meio da certificação [PCI Compliance](https://www.pcisecuritystandards.org), portanto acho melhor manter o copyright aqui dentro por conta de confiança. Mas agradeço a sugestão!
